### ISSUE TITLE
Add syntax highlighting for rules

### ISSUE THREAD

**Issue by bifunctor** [lark-parser/vscode-lark#1]
Should syntax highlighting for rules be included? I've installed the whole syntax highlighting for vscode, and it looks kind of empty.

**Comment by dirk-thomas** [comment]
The whole purpose of this package is to add syntax highlighting for Lark files.

Maybe you can provide an example file you are opening as well as a screenshot what you are seeing.

**Comment by bifunctor** [comment]
[Here][1] is a screenshot of the `calc.py` lark code in the lark example section. All I'm saying is that all the letters highlighted in white makes it look dry...

  [1]: https://imgur.com/a/iFutbuw

**Comment by dirk-thomas** [comment]
The referenced example file contains lark grammar as part of a Python string literal. There is no way for this package to know about the semantic of this string literal.

As the [README](https://github.com/lark-parser/vscode-lark) of this package states:

> The grammars should end with `.lark`.

So if you extract the lark syntax and store it in a file ending in `.lark` the content will be highlighted.
