### ISSUE TITLE
LICENSE Incomplete

### ISSUE THREAD

**Issue by mg-at-yt** [lark-parser/vscode-lark#2]
I would love to use use this extension, but unfortunately require that the LICENSE file be complete.  Currently, the following line which appears toward the bottom of the file has not been filled in, thus making it unusable.
`Copyright [yyyy] [name of copyright owner]`

Please update.

Thank you for your work on this!

**Comment by dirk-thomas** [comment]
I think you are misunderstanding the meaning of this section in the license file. Please see the paragraph above the referenced line:

>      To apply the Apache License to your work, attach the following
>      boilerplate notice, with the fields enclosed by brackets "[]"
>      replaced with your own identifying information. (Don't include
>      the brackets!)  The text should be enclosed in the appropriate
>      comment syntax for the file format. We also recommend that a
>      file or class name and description of purpose be included on the
>      same "printed page" as the copyright notice for easier
>      identification within third-party archives.

My understanding is that the placeholders are not supposed to be substituted in the `LICENSE` file but only where this line is added to source files.

**Comment by mg-at-yt** [comment]
My apologies.  That makes more sense after looking into it further.  I am not used to the appendix being included in the LICENSE file.
